name: example
description: An example.
version: 1.0.0+1
homepage: https://github.com/paulosousadias

publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  imc_def:
    path: ../

dev_dependencies:
  lints: ^4.0.0
