name: imc_def
description: 'This package is a Dart package for IMC messages manipulation. 
  IMC is an open source message protocol specification from
  UPorto-FEUP-LSTS (https://github.com/LSTS/imc).'
version: 4.0.0
homepage: https://github.com/paulosousadias/imc_def_dart
repository: https://github.com/paulosousadias/imc_def_dart

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  
  # built_value: ^8.6.1

  xml: ^6.1.0 # for generator
  crypto: ^3.0.3 # for generator
  yaml: ^3.1.2 # for generator

  collection: ^1.17.2

dev_dependencies:
  test: ^1.24.6

  lints: ^2.1.1

executables:
  imc_generator: 

imc_def:
  imc: lib/xml/IMC.xml
  githash: lsts@6038ec6
  mode: local

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
