name: imc_def
description: 'This package is a Dart package for IMC messages manipulation. 
IMC is an open source message protocol specification from 
UPorto-FEUP-LSTS (https://github.com/LSTS/imc).'
version: 2.0.0-SNAPSHOTnullsafety
homepage: https://github.com/paulosousadias/imc_def_dart
repository: https://github.com/paulosousadias/imc_def_dart

environment:
  sdk: ">=2.6.0 <3.0.0"
#  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  built_value: ^8.0.4

  xml: ^5.0.2 # for generator
  crypto: ^3.0.0 # for generator
  yaml: ^3.1.0 # for generator

  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter  

  pedantic: ^1.9.2

executables:
  imc_generator: 

imc_def:
  imc: xml/IMC.xml
  githash: lsts@f19a343
  mode: local

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - xml/IMC.xml

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
